apiVersion: apps/v1
kind: Deployment
metadata:
  name: devlake
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devlake
  template:
    metadata:
      labels:
        app: devlake
    spec:
      containers:
        - name: devlake
          image: apache/devlake:latest
          ports:
            - containerPort: 8080
          env:
            - name: ENCRYPTION_SECRET
              value: yourStrongSecretHere

---

apiVersion: v1
kind: Service
metadata:
  name: devlake-service
  namespace: argocd
spec:
  selector:
    app: devlake
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
