apiVersion: apps/v1
kind: Deployment
metadata:
  name: devlake
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devlake
  template:
    metadata:
      labels:
        app: devlake
    spec:
      containers:
        - name: devlake
          image: apache/devlake:latest
          ports:
            - containerPort: 8080
          env:
            - name: ENCRYPTION_SECRET
              value: yourStrongSecretHere
            - name: DB_URL
              value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-service.argocd.svc.cluster.local:5432/$(POSTGRES_DB)
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: devlake-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: devlake-db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: devlake-db-secret
                  key: POSTGRES_DB

---

apiVersion: v1
kind: Service
metadata:
  name: devlake-service
  namespace: argocd
spec:
  selector:
    app: devlake
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
